- id: swift-format
  name: swift-format
  entry: swift-format format --in-place --recursive --parallel
  language: swift
  types: [swift]
  require_serial: true
- id: swift-format-lint
  name: swift-format-lint
  entry: swift-format lint --strict --recursive --parallel
  language: swift
  types: [swift]
  require_serial: true
