name: Swift
on:
  push:
    branches: ["wasm32-wasi"]
  pull_request:
    branches: ["wasm32-wasi"]
env:
  SWIFT_SDK_URL: https://github.com/swiftwasm/swift/releases/download/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-08-27-a/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-08-27-a-wasm32-unknown-wasi.artifactbundle.zip
  SWIFT_SDK_CHECKSUM: 6cae1db37d6a975089f5c5b49179bafe7c611c5b92aa93ba03be85928bd9384c
  TARGET_TRIPLE: wasm32-unknown-wasi
jobs:
  build:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy@sha256:29a112d0e2391a07e3cfd810e2e655394c7454983967466f7f8e7b393e7d04c8
    env:
      STACK_SIZE: 524288
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: apt-get update && apt-get install --no-install-recommends -y wabt binaryen
      - run: swift --version
      - run: swift sdk install $SWIFT_SDK_URL --checksum $SWIFT_SDK_CHECKSUM
      - name: Build
        run: |
          swift build --product swift-format --swift-sdk $TARGET_TRIPLE -c release -Xlinker -z -Xlinker stack-size=$STACK_SIZE
          wasm-strip .build/release/swift-format.wasm
          wasm-opt -Oz -all .build/release/swift-format.wasm -o swift-format.wasm
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swift-format.wasm
          path: swift-format.wasm
  test:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy@sha256:29a112d0e2391a07e3cfd810e2e655394c7454983967466f7f8e7b393e7d04c8
    env:
      STACK_SIZE: 4194304
    steps:
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - run: swift --version
      - run: wasmtime -V
      - run: swift sdk install $SWIFT_SDK_URL --checksum $SWIFT_SDK_CHECKSUM
      - run: swift build -c release --build-tests --swift-sdk $TARGET_TRIPLE -Xlinker -z -Xlinker stack-size=$STACK_SIZE
      - run: wasmtime --dir / --wasm max-wasm-stack=$STACK_SIZE .build/release/swift-formatPackageTests.wasm
