name: Swift
on:
  push:
    branches: ["wasm32-wasi"]
  pull_request:
    branches: ["wasm32-wasi"]
jobs:
  build:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy@sha256:216e18ce64ce5f3971f7b381066799acbd61bc34cdcc27f6b251fa299538c1dd
    env:
      STACK_SIZE: 524288
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: apt-get update && apt-get install --no-install-recommends -y wabt binaryen
      - run: swift --version
      - run: swift experimental-sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a-wasm32-unknown-wasi.artifactbundle.zip
      - name: Build
        run: |
          swift build --product swift-format --experimental-swift-sdk wasm32-unknown-wasi -c release -Xlinker -z -Xlinker stack-size=$STACK_SIZE
          wasm-strip .build/release/swift-format.wasm
          wasm-opt -Oz -all .build/release/swift-format.wasm -o swift-format.wasm
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swift-format.wasm
          path: swift-format.wasm
  test:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy@sha256:216e18ce64ce5f3971f7b381066799acbd61bc34cdcc27f6b251fa299538c1dd
    env:
      STACK_SIZE: 4194304
    steps:
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - run: swift --version
      - run: wasmtime -V
      - run: swift experimental-sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a-wasm32-unknown-wasi.artifactbundle.zip
      - run: swift build -c release --build-tests --experimental-swift-sdk wasm32-unknown-wasi -Xlinker -z -Xlinker stack-size=$STACK_SIZE
      - run: wasmtime --dir / --wasm max-wasm-stack=$STACK_SIZE .build/release/swift-formatPackageTests.wasm
